/* 
 * Fax.to REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CountryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CountryApiTests
    {
        private CountryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CountryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CountryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CountryApi
            //Assert.IsInstanceOfType(typeof(CountryApi), instance, "instance is a CountryApi");
        }

        
        /// <summary>
        /// Test AreacodesCountryCodeStateIdGet
        /// </summary>
        [Test]
        public void AreacodesCountryCodeStateIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string countryCode = null;
            //string stateId = null;
            //instance.AreacodesCountryCodeStateIdGet(countryCode, stateId);
            
        }
        
        /// <summary>
        /// Test CountriesCountryCodeDidgroupsGet
        /// </summary>
        [Test]
        public void CountriesCountryCodeDidgroupsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string countryCode = null;
            //string didGroupIds = null;
            //string stateId = null;
            //string cityNamePattern = null;
            //instance.CountriesCountryCodeDidgroupsGet(countryCode, didGroupIds, stateId, cityNamePattern);
            
        }
        
        /// <summary>
        /// Test CountriesDidgroupsDidGroupIdProvisionPost
        /// </summary>
        [Test]
        public void CountriesDidgroupsDidGroupIdProvisionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string didGroupId = null;
            //instance.CountriesDidgroupsDidGroupIdProvisionPost(didGroupId);
            
        }
        
        /// <summary>
        /// Test CountriesGet
        /// </summary>
        [Test]
        public void CountriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.CountriesGet();
            
        }
        
        /// <summary>
        /// Test StatesCountryCodeGet
        /// </summary>
        [Test]
        public void StatesCountryCodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string countryCode = null;
            //instance.StatesCountryCodeGet(countryCode);
            
        }
        
    }

}
