/* 
 * Fax.to REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FaxApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FaxApiTests
    {
        private FaxApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FaxApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FaxApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FaxApi
            //Assert.IsInstanceOfType(typeof(FaxApi), instance, "instance is a FaxApi");
        }

        
        /// <summary>
        /// Test FaxDocumentIdCostsGet
        /// </summary>
        [Test]
        public void FaxDocumentIdCostsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiKey = null;
            //string faxNumber = null;
            //decimal? documentId = null;
            //instance.FaxDocumentIdCostsGet(apiKey, faxNumber, documentId);
            
        }
        
        /// <summary>
        /// Test FaxHistoryGet
        /// </summary>
        [Test]
        public void FaxHistoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiKey = null;
            //string limit = null;
            //string page = null;
            //instance.FaxHistoryGet(apiKey, limit, page);
            
        }
        
        /// <summary>
        /// Test FaxJobIdStatusGet
        /// </summary>
        [Test]
        public void FaxJobIdStatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiKey = null;
            //decimal? jobId = null;
            //instance.FaxJobIdStatusGet(apiKey, jobId);
            
        }
        
        /// <summary>
        /// Test FaxPost
        /// </summary>
        [Test]
        public void FaxPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiKey = null;
            //string faxNumber = null;
            //int? documentId = null;
            //string tsiNumber = null;
            //System.IO.Stream file = null;
            //int? deleteFile = null;
            //instance.FaxPost(apiKey, faxNumber, documentId, tsiNumber, file, deleteFile);
            
        }
        
    }

}
